title: Course GitHub Pages Page
author: Gustavo F. Silva
email: gustafsilva@hotmail.com
description: > # this means to ignore newlines until "baseurl:"
  Website for course github page

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-hacker
